#!/usr/bin/env python3
# coding: utf-8

#----------------------------------------------------
# Imports
#----------------------------------------------------
import os
import sys

#----------------------------------------------------
# Const
#----------------------------------------------------

	IS_PIPED = True if os.fstat(0) != os.fstat(1) else False
	#CAN_TERM = True if
	STDERR   = sys.stderr
	STDOUT   = sys.stdout


	print('Hello, World')

#----------------------------------------------------
# API
#----------------------------------------------------

def env():
  [ print( v, '=', os.getenv(v)) for v in os.environ ] #pythonic for loop

#----------------------------------------------------
# Aux
#----------------------------------------------------

cmd_exists = lambda x: shutil.which(x) is not None

#----------------------------------------------------
# Main
#----------------------------------------------------

	def main():
	  #env()
	  print( support() )

	if __name__ == "__main__": main()
