#!/usr/bin/env bash
##------------------------------------------------------------------------------
##==============================================================================
##     Lux CLI  > lux watch 2 > lux.out  2>&1
##       __
##       \ \
##        \ \
##         > \
##        / ^ \
##       /_/ \_\
##
##  QodeParty (c) 2018
##==============================================================================


#-----------------------------------------------------------
# Script
#-----------------------------------------------------------
	readonly script_pid=$$
	readonly script_author="qodeparty"
	readonly script_id="lux"
	readonly script_prefix="LUX"
	readonly script_rc_file=".luxrc"
	readonly script_log_file="$script_id.log"
	readonly script_lic="MIT License"

	function include(){
		source "${@}"
	}
#-------------------------------------------------------------------------------
# Common Vars
#-------------------------------------------------------------------------------

##--save me
	CPID="$$"

	BIN_DIR="$( cd "$(dirname "$0")" || exit; pwd)"
	THIS_DIR="$( cd $BIN_DIR && cd .. || exit; pwd)"

	opt_verbose=0

	missing=()
	__repo_list=( )
	__alias_list=( )



#-------------------------------------------------------------------------------
# INCLUDES
#-------------------------------------------------------------------------------

	include $BIN_DIR/inc-vars.sh

	include $BIN_DIR/inc-term.sh "${@}"

	include $BIN_DIR/inc-doc.sh

	include $BIN_DIR/inc-utils.sh

	include $BIN_DIR/inc-filetools.sh

	include $BIN_DIR/inc-meta.sh

	include $BIN_DIR/inc-checkup.sh



#-------------------------------------------------------------------------------
# Dispatch
#-------------------------------------------------------------------------------

	include $BIN_DIR/inc-dispatch.sh

#-------------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------------

	function lux_checkup(){

		check_setup
		lux_repair


		check_setup

		#profile_unlink
	}

	function lux_repair(){
		silly "Lux Repairing..."
		lux_pre_config
		lux_pre_config_cli
		lux_pre_config_bash_prof
		lux_pre_config_lux_home
		lux_pre_config_rc_file
		lux_pre_config_bin_dir
		lux_pre_install
	}

	function main(){
		[ -f "$LUX_RC" ] && source $LUX_RC || wtrace "Cant find Lux RC"
		dispatch "$@"
	}

#-------------------------------------------------------------------------------
# Driver
#-------------------------------------------------------------------------------
if [ "$0" = "-bash" ]; then
	:
else

	args=("${@}")

	main "${args[@]}";ret=$?
fi
